pipeline {
    agent {label "agent04"}
    environment {
        VERSION='0.1'
        OCI_URI='registry-vecps-ns.gaccloud.com.cn/tenant-eaws'
    }
    stages {
        stage('Build') {
            steps {
                 withCredentials([usernamePassword(credentialsId: '6cc081dc-8d75-357f-19da-b6374219496f', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''docker login -u=${USERNAME} -p=${PASSWORD} registry-vecps-ns.gaccloud.com.cn
docker build -t ${OCI_URI}/cloud_simpro_front:${VERSION} .
'''
                }
            }
        }
        stage('Check') {
            steps {
                echo "Check"
            }
        }
        stage('Image Push') {
            steps {
                sh '''docker push ${OCI_URI}/cloud_simpro_front:${VERSION}
docker system prune -f
                '''
            }
        }
        stage('Deploy') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'fangzhen02_config', namespace:'',restrictKubeConfigAccess: false, serverUrl: ''){
                    sh '''kubectl get pod -owide
envsubst < cicd/cloud-simpro-front.yaml | kubectl apply -f -
'''
                }
            }
        }
    }
    post {
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                               [pattern: '.propsfile', type: 'EXCLUDE']])
        }
        success {
            echo 'success'
        }
        failure {
            echo 'failure'
        }
    }
}